# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import hackumbc.apps.purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20161002_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to=hackumbc.apps.purchases.models.user_directory_path),
        ),
    ]
