# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20161002_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='name',
            field=models.CharField(default='Default Receipt Name', max_length=64),
            preserve_default=False,
        ),
    ]
